config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "images#new"

  resources :images, only: [:new, :create, :show] do
    member do
      get :compress
      get :convert_to_png
      get :convert_to_bw
    end
  end

  direct :rails_blob do |blob|
    route_for(:rails_service_blob, blob)
  end
  
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  has_one_attached :file

  validates :file, presence: true
  validate :file_must_be_jpeg

  private

  def file_must_be_jpeg
    if file.attached? && !file.content_type.in?(%w(image/jpeg image/jpg))
      errors.add(:file, 'must be a JPEG file')
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:compress, :convert_to_png, :convert_to_bw, :show]
  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      redirect_to @image, notice: "Image uploaded successfully."
    else
      render :new
    end
  end
  
  def show; end

  def compress
    quality = params[:quality].to_i
    compressed_image = compress_image(@image.file, quality)
    send_data compressed_image, type: 'image/jpeg', disposition: 'inline'
  end

  def convert_to_png
    png_image = convert_image_to_png(@image.file)
    send_data png_image, type: 'image/png', disposition: 'inline'
  end

  def convert_to_bw
    bw_image = convert_image_to_bw(@image.file)
    send_data bw_image, type: 'image/jpeg', disposition: 'inline'
  end
  
  private

  def set_image
    @image = Image.find(params[:id])
  end

  def convert_image_to_bw(image)
    image_file = image.blob.download

    img = Magick::Image.from_blob(image_file).first
    img = img.quantize(256, Magick::GRAYColorspace)
    img.to_blob { |attrs| attrs.format = 'JPEG' }
  end
  
  def convert_image_to_png(image)
    image_file = image.blob.download

    img = Magick::Image.from_blob(image_file).first
    img.to_blob { |attrs| attrs.format = 'PNG' }
  end
  
  def compress_image(image, quality)
    image_file = image.blob.download

    img = Magick::Image.from_blob(image_file).first
    img.to_blob { |attrs| attrs.format = 'JPEG'; attrs.quality = quality }
  end

  def image_params
    params.require(:image).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/new.html.erb
<h1>Upload Image</h1>

<% if @image.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</h2>
    <ul>
      <% @image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @image, local: true do |form| %>
  <div class="field">
    <%= form.label :file %>
    <%= form.file_field :file, accept: 'image/jpeg, image/jpg' %>
  </div>

  <div class="actions">
    <%= form.submit "Upload Image", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/images/show.html.erb
<h1>Image Details</h1>
<p>File: <%= image_tag @image.file %></p>

<%= link_to "Convert to Black and White", convert_to_bw_image_path(@image), class: "action-link" %><br>
<%= link_to "Convert to PNG", convert_to_png_image_path(@image), class: "action-link" %><br>

<%= form_with url: compress_image_path(@image), method: :get, id: 'compress-form', data: { controller: 'image', action: 'submit->image#handleSubmit' } do |form| %>
  <div class="form-group">
    <%= form.label :quality, "Compression Quality (1-100):" %>
    <%= form.number_field :quality, in: 1..100, step: 1, id: 'quality-input', data: { image_target: 'qualityInput' }, class: "form-control", required: true %>
  </div>
  <%= form.hidden_field :image_id, value: @image.id, id: 'image-id', data: { image_target: 'imageId' } %>
  <%= form.submit "Compress Image", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageTransformer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>